config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists, shallow: true do
    resources :songs, except: [:index]
  end

  resources :songs, only: [:index]

  resources :playlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name
  
  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs

  has_many :songs, through: :playlist_songs

end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
  belongs_to :artist

  validates_presence_of :title, :length, :play_count

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    cookies[:secret] = "It's a secret to everybody"
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    if @artist.songs.create(song_params)
      redirect_to "/songs"
    else
      render :new
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :play_count, :length, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<h1>All artists</h1>

<%= link_to "Add new artist", new_artist_path %>

<% @artists.each do |artist| %>
<p><%= link_to artist.name, artist_path(artist) %></p>
<% end %>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1> <%= @artist.name %></h1>

<%= link_to "New song", new_artist_song_path(@artist) %>

<% @artist.songs.each do |song| %>
<p> Song: <%= song.title %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBox1804</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline|Montserrat:300" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<header class="header-container">
  <nav>
      <ul>
          <li><a title="Songs">Home</a></li>
          <li><a class="active" title="Playlist">Playlist</a></li>
          <li><a title="Artists">Artists</a></li>
      </ul>
  </nav>
</header>

<h1>Songs</h1>

<div class="song-container">
  <% @songs.each do |song| %>
  <div class="card">
    <div class="card-header">
      <p><%= song.artist.name %></p>
    </div>
    <div class="card-main">
        <%= image_tag("dark_side_of_the_moon.png", alt: "prism-logo", class:"card-logo") %>
      <div class="main-description">
        <p><%= song.title %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<main>
  <h1> Create a Song</h1>
  <div class="container">
      <%= form_for [@artist, @song] do |f| %>
      <div class="form-label top-label">
      <%= f.label :name %>
    </div>
    <div class="form-field-top">
      <%= f.text_field :title, class:"form-field" %>
    </div>
    <div class="form-label">
      <%= f.label :length %>
    </div>
    <div class="form-field-top">
      <%= f.text_field :length, class:"form-field" %>
    </div>
    <div class="form-label">
      <%= f.label :play_count %>
    </div>
    <div class="form-field-top">
      <%= f.text_field :play_count, class:"form-field" %>
    </div>
    <div>
      <%= f.submit "Create song", class:"submit-button"%>
    </div>
  <% end %>
  </div>
</main>